services:
  api:
    image: hng-api:latest
    ports:
      - "8000" 
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - hng-network

  worker:
    image: hng-worker:latest
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - hng-network

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - hng-network

  frontend:
    image: hng-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - hng-network

networks:
  hng-network:
    driver: bridge
